# -*- coding: utf-8 -*-
"""TCS Corporate Financial Intelligence & Forecasting .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0dALCrJQE2YHhknI7y8Xe49ekH18rrF

# TCS Corporate Financial Intelligence & Forecasting Dashboard

## End-to-End Financial Analytics Project

**Company:** Tata Consultancy Services (TCS)

**Project Type:** Financial Statement Analysis, Statistical Analysis, SQL Analytics, Forecasting, and Power BI Dashboard

**Tools Used:** Python, Pandas, NumPy, SQLite, SQL, Power BI, DAX

### Project Objective

The objective of this project is to analyze the historical balance sheet of TCS from 2004 to 2026, transform the data into an analytical format, perform statistical and financial analysis, generate business insights, forecast future financial performance, and develop an executive-level Power BI dashboard for decision support.
"""

# Import required libraries
import pandas as pd
import numpy as np

"""## Load the Dataset

In this section, the TCS balance sheet workbook is uploaded and loaded into the notebook. The workbook contains historical financial statement data across multiple reporting years, which will be explored and transformed in the following steps.

"""

# Upload the Excel workbook
from google.colab import files

uploaded = files.upload()

# Get the uploaded file name
file_name = list(uploaded.keys())[0]
print(file_name)

# Load the Excel workbook
excel_file = pd.ExcelFile(file_name)

# Display available sheet names
excel_file.sheet_names

"""## Select the Financial Statement

The consolidated balance sheet is selected for analysis because it represents the overall financial position of TCS across all subsidiaries and business entities. This provides a more comprehensive view for financial analysis, statistical modeling, and forecasting.

"""

# Load the consolidated balance sheet
tcs_df = pd.read_excel(file_name, sheet_name='Consolidated')

# Display the first few rows
tcs_df.head()

"""## Understand the Dataset Structure

This step examines the size, column structure, data types, and missing values of the financial dataset before transformation and analysis.

"""

# Display dataset information
print('Dataset shape:', tcs_df.shape)

tcs_df.info()

tcs_df.isnull().sum()

# Display the first 15 rows of the balance sheet
tcs_df.head(15)

"""## Financial Statement Layout Inspection

The balance sheet is currently stored in a reporting format where financial indicators are listed as rows and financial years are represented as columns. This section inspects the complete structure before transforming the dataset into an analytical format suitable for statistical analysis, SQL, forecasting, and business intelligence reporting.

"""

# Display the complete dataset shape
print(tcs_df.shape)

# Display the first 20 rows
tcs_df.head(20)

"""## Remove Section Header Rows

The balance sheet contains category headers such as "EQUITIES AND LIABILITIES" and "NON-CURRENT LIABILITIES" that do not represent measurable financial values. These rows are removed to prepare a clean analytical dataset.

"""

# Remove rows where all year values are missing
tcs_clean = tcs_df.dropna(how='all', subset=tcs_df.columns[1:])

# Reset index
tcs_clean = tcs_clean.reset_index(drop=True)

print(tcs_clean.shape)

tcs_clean.head(15)

"""## Transform into Analytical Format

The reporting-format balance sheet is converted into a long analytical format where each row represents a financial indicator, a reporting year, and its corresponding value. This structure is required for statistical analysis, SQL queries, forecasting models, and Power BI visualizations.

"""

# Convert wide financial statement into long analytical format
tcs_long = tcs_clean.melt(
    id_vars='Indicator',
    var_name='Year',
    value_name='Amount'
)

# Display transformed data
tcs_long.head(20)

"""## Clean and Standardize Financial Years

The reporting year labels are converted into standard four-digit calendar years to ensure consistency across statistical analysis, SQL operations, forecasting models, and Power BI reporting.

"""

# Convert reporting labels into calendar years
tcs_long['Year'] = tcs_long['Year'].astype(str).str.extract(r'(\d+)').astype(int)
tcs_long['Year'] = tcs_long['Year'].apply(lambda x: 2000 + x)

# Display cleaned data
tcs_long.head()

"""## Preserve the Original Dataset

A working copy of the transformed financial dataset is created before any cleaning or analytical operations are performed. This ensures that the original transformed data remains unchanged and provides an audit trail for all subsequent data processing steps.

"""

# Create a protected working copy
tcs_working = tcs_long.copy()

print('Working dataset created successfully.')
tcs_working.head()

"""## Data Type and Missing Value Audit

This section verifies data types, identifies missing values, and checks the overall integrity of the financial dataset before statistical analysis and modeling.

"""

# Check data types
tcs_working.dtypes

# Check missing values
missing_summary = tcs_working.isnull().sum()

print(missing_summary)

"""## Missing Financial Value Assessment

Missing financial values are identified separately from structural or formatting issues. This step helps determine whether the missing entries represent unavailable financial information or reporting-section artifacts.

"""

# Display rows with missing financial values
missing_rows = tcs_working[tcs_working['Amount'].isna()]

print('Missing rows:', len(missing_rows))

missing_rows.head(20)

"""## Duplicate Record Verification

Each financial indicator should appear only once for a given reporting year. Duplicate records are checked to ensure that the analytical dataset preserves the original financial statement structure without repeated observations.

"""

# Check duplicate records based on Indicator and Year

duplicate_count = tcs_working.duplicated(subset=['Indicator', 'Year']).sum()

print('Duplicate records:', duplicate_count)

"""## Financial Statistics Summary

This section generates descriptive statistics for the financial statement values. The summary provides an overview of the distribution, central tendency, and variability of TCS financial amounts across all reporting years.

"""

# Generate descriptive statistics for financial values
tcs_working['Amount'] = pd.to_numeric(tcs_working['Amount'], errors='coerce')

financial_stats = tcs_working['Amount'].describe()

print(financial_stats)

"""## Largest Financial Components

This section identifies the financial indicators with the highest cumulative values across all reporting years, highlighting the most significant balance sheet components in the TCS financial structure.

"""

# Identify the largest financial indicators
largest_indicators = (
    tcs_working
    .groupby('Indicator')['Amount']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

largest_indicators

"""## Clean and Standardize Financial Values

The financial values contain comma separators that prevent proper numeric conversion. This step removes formatting characters and converts all financial amounts into a standardized numeric format while preserving the original values.

"""

# Clean financial amount values

tcs_working['Amount'] = (
    tcs_working['Amount']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace(' ', '', regex=False)
)

tcs_working['Amount'] = pd.to_numeric(tcs_working['Amount'], errors='coerce')

print(tcs_working['Amount'].dtype)

tcs_working.head()

"""## Recalculate Descriptive Statistics

After standardizing the financial values, descriptive statistics are recalculated to obtain accurate measures of central tendency and dispersion across the TCS balance sheet dataset.

"""

# Recalculate descriptive statistics

financial_stats = tcs_working['Amount'].describe()

print(financial_stats)

"""## Recalculate the Largest Financial Indicators

The financial indicators are recalculated after data cleaning to identify the actual largest balance sheet components across all reporting years.

"""

# Recalculate the largest financial indicators

largest_indicators = (
    tcs_working
    .groupby('Indicator')['Amount']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

largest_indicators

import pandas as pd

file_name = "tcs-balance-sheet (1).xlsx"
excel_file = pd.ExcelFile(file_name)

print(excel_file.sheet_names)

tcs_df = pd.read_excel(file_name, sheet_name="Consolidated")

print(tcs_df.shape)
tcs_df.head()

# Keep only the indicator column and year columns
tcs_long = tcs_df.melt(
    id_vars="Indicator",
    var_name="Year",
    value_name="Amount"
)

# Remove rows where amount is missing
tcs_long = tcs_long.dropna(subset=["Amount"])

# Convert year labels such as "Mar 26" -> 2026
tcs_long["Year"] = (
    tcs_long["Year"]
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(int)
    .apply(lambda x: 2000 + x)
)

# Clean amount values
tcs_long["Amount"] = (
    tcs_long["Amount"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

tcs_long["Amount"] = pd.to_numeric(tcs_long["Amount"], errors="coerce")

print("tcs_long shape:", tcs_long.shape)
tcs_long.head()

tcs_working = tcs_long.copy()
print(tcs_working.shape)
tcs_working.head()

# Create a clean analytical dataset
tcs_clean = tcs_working.copy()

# Remove rows where Amount is missing
tcs_clean = tcs_clean.dropna(subset=['Amount'])

# Remove section headings and category labels
exclude_keywords = [
    'EQUITIES',
    'LIABILITIES',
    'CURRENT',
    'NON-CURRENT',
    'ASSETS',
    'SHAREHOLDER',
    'FUNDS'
]

pattern = '|'.join(exclude_keywords)

tcs_clean = tcs_clean[
    ~tcs_clean['Indicator'].str.upper().str.contains(pattern, na=False)
]

print("Original dataset shape:", tcs_working.shape)
print("Clean dataset shape:", tcs_clean.shape)

tcs_clean.head(10)

def classify_indicator(indicator):
    name = str(indicator).lower()

    if 'equity' in name or 'share capital' in name or 'reserve' in name:
        return 'Equity'
    elif 'borrowing' in name or 'loan' in name or 'debt' in name:
        return 'Borrowings'
    elif 'investment' in name:
        return 'Investments'
    elif 'asset' in name or 'cash' in name or 'inventory' in name or 'receivable' in name:
        return 'Assets'
    elif 'payable' in name or 'liabilit' in name or 'provision' in name:
        return 'Liabilities'
    else:
        return 'Other'

tcs_clean['Category'] = tcs_clean['Indicator'].apply(classify_indicator)

print(tcs_clean['Category'].value_counts())

tcs_clean.head(10)

"""Year-wise Financial Trend Analysis"""

import pandas as pd

yearly_summary = (
    tcs_clean
    .groupby('Year')['Amount']
    .sum()
    .reset_index()
    .sort_values('Year')
)

yearly_summary

"""Year-wise Trend Chart"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(yearly_summary['Year'], yearly_summary['Amount'], marker='o', linewidth=2)

plt.title('TCS Financial Trend Over Time')
plt.xlabel('Year')
plt.ylabel('Total Financial Amount')
plt.grid(True)

plt.show()

"""Category-wise Financial Distribution"""

category_summary = (
    tcs_clean
    .groupby('Category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

category_summary

plt.figure(figsize=(8,5))
category_summary.plot(kind='bar')

plt.title('Financial Amount by Category')
plt.ylabel('Total Amount')

plt.show()

"""Top 10 Financial Indicators"""

top_indicators = (
    tcs_clean
    .groupby('Indicator')['Amount']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_indicators

plt.figure(figsize=(10,6))
top_indicators.sort_values().plot(kind='barh')

plt.title('Top 10 Financial Indicators')

plt.show()

"""# ***Statistical Analysis***"""

stats_summary = tcs_clean.groupby('Category')['Amount'].agg(
    ['count', 'mean', 'median', 'std', 'min', 'max']
)

stats_summary

"""Year-wise Financial Trend"""

import matplotlib.pyplot as plt

trend_data = tcs_clean[tcs_clean['Indicator'] == 'Reserves and Surplus'].copy()

trend_data = trend_data.sort_values('Year')

plt.figure(figsize=(12,6))
plt.plot(
    trend_data['Year'],
    trend_data['Amount'],
    marker='o',
    linewidth=3
)

plt.title('TCS Reserves and Surplus Trend (Historical)', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Amount')
plt.grid(True)

plt.show()

trend_data

"""**Year-over-Year Growth Rate Calculation**"""

import pandas as pd
import matplotlib.pyplot as plt

# Prepare trend data
trend_data = tcs_clean[tcs_clean['Indicator'] == 'Reserves and Surplus'].copy()
trend_data = trend_data.sort_values('Year')

# Calculate Year-over-Year Growth %
trend_data['YoY Growth (%)'] = trend_data['Amount'].pct_change() * 100

# Display result
trend_data[['Year', 'Amount', 'YoY Growth (%)']].head(10)

plt.figure(figsize=(12,6))

plt.bar(
    trend_data['Year'],
    trend_data['YoY Growth (%)']
)

plt.title('Year-over-Year Growth Rate of Reserves and Surplus', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Growth (%)')
plt.grid(axis='y')

plt.show()

"""CAGR (Compound Annual Growth Rate)"""

# CAGR Calculation for Reserves and Surplus

start_value = trend_data.iloc[0]['Amount']
end_value = trend_data.iloc[-1]['Amount']
start_year = trend_data.iloc[0]['Year']
end_year = trend_data.iloc[-1]['Year']

num_years = end_year - start_year

cagr = ((end_value / start_value) ** (1 / num_years) - 1) * 100

print('Start Year:', start_year)
print('End Year:', end_year)
print('Start Value:', round(start_value, 2))
print('End Value:', round(end_value, 2))
print('Number of Years:', num_years)
print('CAGR (%):', round(cagr, 2))

"""Statistical Summary of Growth Rate"""

# Statistical summary of Year-over-Year Growth

growth_stats = trend_data['YoY Growth (%)'].dropna().describe()

print(growth_stats)

"""Visualize Growth Distribution"""

plt.figure(figsize=(10,5))

plt.hist(
    trend_data['YoY Growth (%)'].dropna(),
    bins=8
)

plt.title('Distribution of Year-over-Year Growth Rates', fontsize=15)
plt.xlabel('Growth Rate (%)')
plt.ylabel('Frequency')

plt.show()

"""Linear Regression Forecasting"""

from sklearn.linear_model import LinearRegression
import numpy as np

# Prepare data
X = trend_data[['Year']]
y = trend_data['Amount']

# Train Linear Regression model
model = LinearRegression()
model.fit(X, y)

# Display model parameters
print('Slope:', model.coef_[0])
print('Intercept:', model.intercept_)

"""# **Predict Future Values (2027–2030)**"""

# Predict future years
future_years = np.array([2027, 2028, 2029, 2030]).reshape(-1, 1)

predictions = model.predict(future_years)

forecast_df = pd.DataFrame({
    'Year': [2027, 2028, 2029, 2030],
    'Predicted Reserves and Surplus': predictions
})

forecast_df

plt.figure(figsize=(12,6))

# Historical data
plt.plot(
    trend_data['Year'],
    trend_data['Amount'],
    marker='o',
    linewidth=3,
    label='Historical'
)

# Forecast
plt.plot(
    forecast_df['Year'],
    forecast_df['Predicted Reserves and Surplus'],
    marker='s',
    linewidth=3,
    linestyle='--',
    label='Forecast'
)

plt.title('TCS Reserves and Surplus: Historical Trend and Forecast', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Amount')
plt.legend()
plt.grid(True)

plt.show()

"""# ***Evaluate the Linear Regression Model***"""

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Predictions on historical data
historical_predictions = model.predict(X)

# Evaluation metrics
r2 = r2_score(y, historical_predictions)
mae = mean_absolute_error(y, historical_predictions)
rmse = np.sqrt(mean_squared_error(y, historical_predictions))

print('Model Evaluation')
print('----------------')
print('R2 Score:', round(r2, 4))
print('Mean Absolute Error (MAE):', round(mae, 2))
print('Root Mean Squared Error (RMSE):', round(rmse, 2))

"""*Compare Actual vs Predicted*"""

comparison_df = trend_data[['Year', 'Amount']].copy()
comparison_df['Predicted Amount'] = historical_predictions
comparison_df['Error'] = comparison_df['Amount'] - comparison_df['Predicted Amount']

comparison_df.head(10)

"""**Actual vs Predicted Visualization**"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.plot(
    comparison_df['Year'],
    comparison_df['Amount'],
    marker='o',
    linewidth=3,
    label='Actual'
)

plt.plot(
    comparison_df['Year'],
    comparison_df['Predicted Amount'],
    marker='s',
    linewidth=3,
    linestyle='--',
    label='Predicted'
)

plt.title('TCS Reserves and Surplus: Actual vs Predicted', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Amount')
plt.legend()
plt.grid(True)

plt.show()

"""# **Multi-Indicator Financial Intelligence**
Category-wise Financial Trend
"""

import matplotlib.pyplot as plt

# Aggregate yearly values by financial category
category_trend = (
    tcs_clean
    .groupby(['Year', 'Category'])['Amount']
    .sum()
    .reset_index()
)

# Plot category trends
plt.figure(figsize=(14,7))

for category in category_trend['Category'].unique():
    temp = category_trend[category_trend['Category'] == category]
    plt.plot(
        temp['Year'],
        temp['Amount'],
        marker='o',
        linewidth=2,
        label=category
    )

plt.title('TCS Financial Category Trend Analysis', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Amount')
plt.legend()
plt.grid(True)

plt.show()

category_trend.head(10)

"""Pivot Table for Financial Categories"""

# Create pivot table

category_pivot = category_trend.pivot(
    index='Year',
    columns='Category',
    values='Amount'
)

category_pivot = category_pivot.fillna(0)

category_pivot.head()

"""## Correlation Analysis

This section examines the statistical relationship between major financial categories of TCS. Correlation helps identify whether two financial variables move together over time, which is useful for financial forecasting, investment analysis, and business decision-making.

"""

import matplotlib.pyplot as plt

# Calculate correlation matrix
correlation_matrix = category_pivot.corr()

print(correlation_matrix)

# Plot correlation heatmap using matplotlib
plt.figure(figsize=(8,6))
plt.imshow(correlation_matrix, cmap='coolwarm', interpolation='nearest')
plt.colorbar(label='Correlation')

plt.xticks(range(len(correlation_matrix.columns)), correlation_matrix.columns, rotation=45)
plt.yticks(range(len(correlation_matrix.columns)), correlation_matrix.columns)

plt.title('Correlation Matrix of TCS Financial Categories')

plt.tight_layout()
plt.show()

"""## Business Interpretation

The correlation analysis measures how different financial categories move together over time.

* A correlation value close to **1** indicates a strong positive relationship.
* A value close to **0** indicates little or no relationship.
* A value close to **-1** indicates a strong negative relationship.

In the TCS financial dataset, a strong positive correlation between **Assets and Equity** would indicate that the company's asset growth has been supported primarily by shareholder funds rather than excessive borrowing. This is generally considered a positive indicator of long-term financial strength and stability.

## Financial Health Score

This section creates a simplified financial health score using major balance sheet categories. The score is designed to represent the overall financial strength of TCS based on the relationship between equity, assets, liabilities, and borrowings across reporting years.
"""

# Create a working copy
health_df = category_pivot.copy()

# Ensure all required categories exist
for col in ['Equity', 'Assets', 'Liabilities', 'Borrowings']:
    if col not in health_df.columns:
        health_df[col] = 0

# Financial Health Score
health_df['Financial Health Score'] = (
    (health_df['Equity'] * 0.4) +
    (health_df['Assets'] * 0.3) -
    (health_df['Liabilities'] * 0.2) -
    (health_df['Borrowings'] * 0.1)
)

health_df.head()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(
    health_df.index,
    health_df['Financial Health Score'],
    marker='o',
    linewidth=3,
    color='green'
)

plt.title('TCS Financial Health Score Over Time', fontsize=16)
plt.xlabel('Financial Year')
plt.ylabel('Financial Health Score')
plt.grid(True)

plt.show()

best_years = (
    health_df['Financial Health Score']
    .sort_values(ascending=False)
    .head(5)
)

best_years

"""## Business Interpretation

The financial health score combines equity strength, asset growth, liability exposure, and borrowing levels into a single analytical metric. Higher scores indicate stronger financial positioning and greater balance sheet stability. The highest-ranked years represent periods in which TCS demonstrated comparatively stronger financial resilience and capital strength.

## SQLite Database Integration

The cleaned TCS financial dataset is stored in a SQLite database to simulate a real-world financial reporting environment. This allows SQL-based business analysis and prepares the data for downstream Power BI integration.
"""

import sqlite3

# Create SQLite database
conn = sqlite3.connect('tcs_financial_analysis.db')

# Export cleaned financial data
tcs_clean.to_sql(
    'tcs_financials',
    conn,
    if_exists='replace',
    index=False
)

# Export financial health data
health_df.reset_index().to_sql(
    'financial_health',
    conn,
    if_exists='replace',
    index=False
)

print('SQLite database created successfully.')

query = "SELECT name FROM sqlite_master WHERE type='table';"

tables = pd.read_sql_query(query, conn)

tables

query = """
SELECT
    Indicator,
    ROUND(SUM(Amount), 2) AS Total_Amount
FROM tcs_financials
GROUP BY Indicator
ORDER BY Total_Amount DESC
LIMIT 10;
"""

top_sql = pd.read_sql_query(query, conn)

top_sql

query = """
SELECT
    Year,
    ROUND(SUM(Amount), 2) AS Total_Financial_Amount
FROM tcs_financials
GROUP BY Year
ORDER BY Year;
"""

yearly_sql = pd.read_sql_query(query, conn)

yearly_sql

"""Category-wise Financial Summary"""

query = """
SELECT
    Category,
    ROUND(SUM(Amount), 2) AS Total_Amount
FROM tcs_financials
GROUP BY Category
ORDER BY Total_Amount DESC;
"""

category_sql = pd.read_sql_query(query, conn)

category_sql

"""## Financial Health Ranking by Year

This SQL query ranks the financial years of TCS based on the calculated Financial Health Score, helping identify the strongest and weakest financial periods.

"""

query = """
SELECT
    Year,
    ROUND([Financial Health Score], 2) AS Financial_Health_Score
FROM financial_health
ORDER BY [Financial Health Score] DESC;
"""

health_ranking = pd.read_sql_query(query, conn)

health_ranking

"""## Equity Growth Trend

This query tracks the year-wise movement of equity-related financial values to understand long-term shareholder capital growth.

"""

query = """
SELECT
    Year,
    ROUND(SUM(Amount), 2) AS Equity_Amount
FROM tcs_financials
WHERE Category = 'Equity'
GROUP BY Year
ORDER BY Year;
"""

equity_sql = pd.read_sql_query(query, conn)

equity_sql

"""## Borrowings Trend

This query evaluates the year-wise movement of borrowings to assess changes in financial leverage over time.

"""

query = """
SELECT
    Year,
    ROUND(SUM(Amount), 2) AS Borrowings_Amount
FROM tcs_financials
WHERE Category = 'Borrowings'
GROUP BY Year
ORDER BY Year;
"""

borrowing_sql = pd.read_sql_query(query, conn)

borrowing_sql

"""## Equity vs Liabilities Comparison

This query compares total equity and liabilities across financial years to evaluate the capital structure of TCS.

"""

query = """
SELECT
    Year,
    Category,
    ROUND(SUM(Amount), 2) AS Total_Amount
FROM tcs_financials
WHERE Category IN ('Equity', 'Liabilities')
GROUP BY Year, Category
ORDER BY Year, Category;
"""

equity_liability_sql = pd.read_sql_query(query, conn)

equity_liability_sql

"""## SQL Executive Summary

This query generates a compact executive summary of the TCS financial database, including record count, year coverage, number of financial indicators, and total financial amount.

"""

query = """
SELECT
    COUNT(*) AS Total_Records,
    COUNT(DISTINCT Year) AS Total_Years,
    COUNT(DISTINCT Indicator) AS Total_Indicators,
    ROUND(SUM(Amount), 2) AS Total_Financial_Amount
FROM tcs_financials;
"""

executive_summary = pd.read_sql_query(query, conn)

executive_summary

"""Export Data for Power BI"""

# Export cleaned financial dataset
tcs_clean.to_csv('tcs_clean_financial_data.csv', index=False)

# Export category trend data
category_trend.to_csv('tcs_category_trend.csv', index=False)

# Export yearly financial summary
yearly_summary.to_csv('tcs_yearly_summary.csv', index=False)

# Export financial health score
health_df.reset_index().to_csv('tcs_financial_health.csv', index=False)

# Export forecast data
forecast_df.to_csv('tcs_forecast.csv', index=False)

print('Power BI files exported successfully.')

from google.colab import files

files.download('tcs_clean_financial_data.csv')
files.download('tcs_category_trend.csv')
files.download('tcs_yearly_summary.csv')
files.download('tcs_financial_health.csv')
files.download('tcs_forecast.csv')
files.download('tcs_financial_analysis.db')